name: BlackPower
author: BlackTure
description: A SF expansion 
main: io.github.thebusybiscuit.ecopower.EcoPowerPlugin
website: https://github.com/TheBusyBiscuit/EcoPower

depend: [Slimefun]

version: ${project.version}
api-version: 1.14
